name: The Internet
on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/the-internet.yml'
      - 'the-internet/utils/**'
      - 'the-internet/page-objects/**'
      - 'the-internet/fixtures/**'
      - 'the-internet/tests/**'
      - 'package.json'
      - 'package-lock.json'
      - 'playwright.config.ts'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/the-internet.yml'
      - 'the-internet/utils/**'
      - 'the-internet/page-objects/**'
      - 'the-internet/fixtures/**'
      - 'the-internet/tests/**'
      - 'package.json'
      - 'package-lock.json'
      - 'playwright.config.ts'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test the-internet
      env:
        TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-the-internet
        path: playwright-report/
        retention-days: 3
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: test-results-the-internet
        path: test-results/
        retention-days: 3
